use clarity::vm::database::{
    ClarityBackingStore, ClarityDatabase, MemoryBackingStore, NULL_BURN_STATE_DB, NULL_HEADER_DB,
};
use clarity::vm::errors::VmExecutionError;
use clarity::vm::types::QualifiedContractIdentifier;
use rusqlite::Connection;
use stacks_common::types::chainstate::{StacksBlockId, TrieHash};
use stacks_common::util::hash::Sha512Trunc256Sum;

/// Bytes read from and written to the backing store during a run.
#[derive(Debug, Clone, Copy, Default)]
pub struct StoreByteCounts {
    pub bytes_read: u64,
    pub bytes_written: u64,
}

/// Wraps a `MemoryBackingStore` and counts the payload bytes that flow through
/// it during Clarity execution. Only the value bytes are counted (not keys),
/// since keys are fixed-shape strings generated by the VM.
pub struct CountingStore<'a> {
    inner: &'a mut MemoryBackingStore,
    bytes_read: u64,
    bytes_written: u64,
}

impl<'a> CountingStore<'a> {
    pub fn new(inner: &'a mut MemoryBackingStore) -> Self {
        Self {
            inner,
            bytes_read: 0,
            bytes_written: 0,
        }
    }

    pub fn counts(&self) -> StoreByteCounts {
        StoreByteCounts {
            bytes_read: self.bytes_read,
            bytes_written: self.bytes_written,
        }
    }

    pub fn as_clarity_db(&mut self) -> ClarityDatabase<'_> {
        ClarityDatabase::new(self, &NULL_HEADER_DB, &NULL_BURN_STATE_DB)
    }
}

impl ClarityBackingStore for CountingStore<'_> {
    fn put_all_data(&mut self, items: Vec<(String, String)>) -> Result<(), VmExecutionError> {
        for (_, v) in &items {
            self.bytes_written += v.len() as u64;
        }
        self.inner.put_all_data(items)
    }

    fn get_data(&mut self, key: &str) -> Result<Option<String>, VmExecutionError> {
        let result = self.inner.get_data(key)?;
        if let Some(ref v) = result {
            self.bytes_read += v.len() as u64;
        }
        Ok(result)
    }

    fn get_data_from_path(&mut self, hash: &TrieHash) -> Result<Option<String>, VmExecutionError> {
        let result = self.inner.get_data_from_path(hash)?;
        if let Some(ref v) = result {
            self.bytes_read += v.len() as u64;
        }
        Ok(result)
    }

    fn get_data_with_proof(
        &mut self,
        key: &str,
    ) -> Result<Option<(String, Vec<u8>)>, VmExecutionError> {
        let result = self.inner.get_data_with_proof(key)?;
        if let Some((ref v, _)) = result {
            self.bytes_read += v.len() as u64;
        }
        Ok(result)
    }

    fn get_data_with_proof_from_path(
        &mut self,
        hash: &TrieHash,
    ) -> Result<Option<(String, Vec<u8>)>, VmExecutionError> {
        let result = self.inner.get_data_with_proof_from_path(hash)?;
        if let Some((ref v, _)) = result {
            self.bytes_read += v.len() as u64;
        }
        Ok(result)
    }

    fn set_block_hash(&mut self, bhh: StacksBlockId) -> Result<StacksBlockId, VmExecutionError> {
        self.inner.set_block_hash(bhh)
    }

    fn get_block_at_height(&mut self, height: u32) -> Option<StacksBlockId> {
        self.inner.get_block_at_height(height)
    }

    fn get_current_block_height(&mut self) -> u32 {
        self.inner.get_current_block_height()
    }

    fn get_open_chain_tip_height(&mut self) -> u32 {
        self.inner.get_open_chain_tip_height()
    }

    fn get_open_chain_tip(&mut self) -> StacksBlockId {
        self.inner.get_open_chain_tip()
    }

    fn get_side_store(&mut self) -> &Connection {
        self.inner.get_side_store()
    }

    fn get_contract_hash(
        &mut self,
        contract: &QualifiedContractIdentifier,
    ) -> Result<(StacksBlockId, Sha512Trunc256Sum), VmExecutionError> {
        self.inner.get_contract_hash(contract)
    }

    fn insert_metadata(
        &mut self,
        contract: &QualifiedContractIdentifier,
        key: &str,
        value: &str,
    ) -> Result<(), VmExecutionError> {
        self.bytes_written += value.len() as u64;
        self.inner.insert_metadata(contract, key, value)
    }

    fn get_metadata(
        &mut self,
        contract: &QualifiedContractIdentifier,
        key: &str,
    ) -> Result<Option<String>, VmExecutionError> {
        let result = self.inner.get_metadata(contract, key)?;
        if let Some(ref v) = result {
            self.bytes_read += v.len() as u64;
        }
        Ok(result)
    }

    fn get_metadata_manual(
        &mut self,
        at_height: u32,
        contract: &QualifiedContractIdentifier,
        key: &str,
    ) -> Result<Option<String>, VmExecutionError> {
        let result = self.inner.get_metadata_manual(at_height, contract, key)?;
        if let Some(ref v) = result {
            self.bytes_read += v.len() as u64;
        }
        Ok(result)
    }
}
